spring.application.name=OuvirFrase

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/ouvirfrase
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true