CREATE TABLE video (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       youtube_id VARCHAR(20)  NOT NULL UNIQUE,
                       titulo     VARCHAR(300) NOT NULL,
                       idioma     VARCHAR(10)  NOT NULL
);

CREATE TABLE trecho (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        video_id    BIGINT           NOT NULL REFERENCES video (id),
                        ordem       INTEGER          NOT NULL,
                        texto       VARCHAR(1000)    NOT NULL,
                        inicio_seg  DOUBLE PRECISION NOT NULL,
                        duracao_seg DOUBLE PRECISION NOT NULL,
                        UNIQUE (video_id, ordem)
);

CREATE SEQUENCE ocorrencia_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE ocorrencia (
                            id         BIGINT PRIMARY KEY,
                            video_id   BIGINT           NOT NULL REFERENCES video (id),
                            trecho_id  BIGINT           NOT NULL REFERENCES trecho (id),
                            palavra    VARCHAR(100)     NOT NULL,
                            posicao    INTEGER          NOT NULL,
                            inicio_seg DOUBLE PRECISION NOT NULL,
                            UNIQUE (video_id, posicao)
);

CREATE INDEX idx_ocorrencia_palavra ON ocorrencia (palavra, video_id, posicao);